### ISSUE TITLE
Make the progress-bar more nuanced than in steps of 1% from 0% to 100%

### ISSUE THREAD

**Issue by joshinils** [slhck/ffmpeg-progress-yield#12]
**Is your feature request related to a problem? Please describe.**
When watching the normalization progress on a slow machine for a large file (like a Blu-ray movie) the time between single percent increases is too slow for my liking.

**Describe the solution you'd like**
why is this line in ~/.local/lib/python3.10/site-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py:
`yield int(elapsed_time / total_dur * 100)` 
creating an int?

I gather from the source I've read so far (and what I understood) that you parse the ffmpeg progress output time string and from that calculate the point in the duration of the stream of the file.
Can this not be done as a float? Is the display of a float not a better thing to have?
How often do you update this number? I don't know if that could be a drawback.

**Additional context**
I created a custom script which I can `watch`. It parses the progress output of ffmpeg-normalize (redirected into a log-file) to make it "more nice" and more like I want it, for that reason it would be nice to have more precise values than in steps of 1.
Since the calls for one file take so long, the time between increases of 1% is larger than I would like. Normalizing a whole movie on my NAS-machine takes multiple hours, so it takes several minutes for a percent to get done.

Of course, this script is very personalized with probably far too many hard coded things:
https://github.com/joshinils/bin_shell/blob/master/format_normalize_progress.py

This is the script with which I _was_ starting the normalization procedure.
https://github.com/joshinils/bin_shell/blob/master/normalize

I am in the process of re-writing it in python to be able to set a different bitrate per stream depending on the channel-layout of it, because of slhck/ffmpeg-normalize#232
https://github.com/joshinils/bin_shell/blob/master/normalize.py
Which is probably all sorts of bad code and not optimal, but it works, for now.

**Comment by slhck** [comment]
Moved this issue here, as it's a function of this project.

**Comment by slhck** [comment]
Will make a new release of ffmpeg-normalize in a few minutes.

**Comment by joshinils** [comment]
thank you very much.
```
Stream 1/1:  14%|█▍        | 14.177270684137696/100 [08:26<59:45, 41.78s/it][A

Stream 1/1:  14%|█▍        | 14.19241500561823/100 [08:26<57:01, 39.88s/it] [A

Stream 1/1:  14%|█▍        | 14.207559327098766/100 [08:27<54:23, 38.04s/it][A

Stream 1/1:  14%|█▍        | 14.238940859238841/100 [08:28<51:58, 36.36s/it][A

Stream 1/1:  14%|█▍        | 14.25439743477052/100 [08:28<51:00, 35.69s/it] [A

Stream 1/1:  14%|█▍        | 14.270010137327771/100 [08:29<50:19, 35.23s/it][A
```
I think you should still limit the number of digits, though?
I mean, it's nice to have this much precision, no doubt. (and I don't see it because of my script, which parses it away behind the scenes)
But I think someone else might complain.

The total number of digits seems to vary, which means the progress bar will look like it flickers.
I think 2 or 3 significant digits after the decimal point should be enough. So something like `f"{percent:7.3f}"`

**Comment by slhck** [comment]
Hmm. I thought that tqdm would handle this more gracefully. I'll see if I can round it myself before passing the percentage. Thanks for letting me know!

**Comment by slhck** [comment]
FIxed in the latest release.

**Comment by slhck** [comment]
That was probably not intended, as the remaining API was using floats. Thanks for catching this. Made a new release for this lib, and fixed it upstream: https://github.com/slhck/ffmpeg-normalize/commit/d21b49d0e3a3508fa6f1ed52ca233cd800e8bce5

Should be working in latest `ffmpeg-normalize` like this:

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/6c5e7cd3-9363-4881-b0a9-8a7f9abee2da">
