### ISSUE TITLE
Progressbar is printed twice

### ISSUE THREAD

**Issue by HeIIow2** [slhck/ffmpeg-progress-yield#16]
Hi,

First of all a HUUGE thank you to you, for providing this skript, it REALLY helps <333

---

I am running an ffmpeg command with a progressbar, just like you showed in the documentation.

```python
    # build the ffmpeg command
    ffmpeg_command = [
        "ffmpeg", 
        "-i", str(target.file_path), 
        "-af", select, 
        "-b", str(bitrate_b),
        str(output_target.file_path)
    ]

    # run the ffmpeg command with a progressbar
    ff = FfmpegProgress(ffmpeg_command)
    with tqdm(total=100, position=1, desc="ffmpeg") as pbar:
        for progress in ff.run_command_with_progress():
            pbar.update(progress - pbar.n)

    LOGGER.debug(ff.stderr)
```

But a little bit before it is finished, a second progressbar appears, and I have no clue as to why this might be:

```
Downloading:
Album("HERZSTILLSTAND") by Artist(ZOMBIEZ) under Label()

HERZSTILLSTAND:  96%|████████████████████████████████████████████████████████████████████████████████████████▏   | 1.28M/1.34M [01:52<00:04, 12.0kB/s]
ffmpeg: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:04<00:00, 20.02it/s]
ffmpeg:  90%|███████████████████████████████████████████████████████████████████████████████████████████▎         | 90.38/100 [00:04<00:00, 20.25it/s]
Album("HERZSTILLSTAND") by Artist(ZOMBIEZ) under Label()
0 from 1 downloads failed:
successrate:	100%
failrate:	0%
total size:	3.19 mB
```

I am just copying some more output than the two pb, for some context. The first progressbar is the downloading, so it is irrelevant. The second and third progressbars are the ffmpeg progressbars. I hope you can help me without much trouble.

Have a nice day :3

**Comment by slhck** [comment]
Sorry, it's hard to diagnose without the complete program and information about the exact packages you are using. So far I haven't observed an error with two progress bars appearing.

Try replacing the `for progress … ` with a simple loop that sleeps for a bit between each iteration. Does the problem still exist?

Do you have a complete reproducible example for me?

**Comment by HeIIow2** [comment]
Hi,

Thank you very much for the swift reply. I don't know what the issue was, but I just "*copied*" the progressbar code of my other progressbar over, modified it, and it ended up working:

```python
    # run the ffmpeg command with a progressbar
    ff = FfmpegProgress(ffmpeg_command)
    with tqdm(total=100, desc="ffmpeg") as pbar:
        for progress in ff.run_command_with_progress():
            pbar.update(int(progress)-pbar.n)
``` 

I guess it was the position.
*Mow you know, if another person has a similar issue!*

Thank youuu :)

**Comment by slhck** [comment]
Sure, you're welcome!
