### ISSUE TITLE
Use creationflags to hide the console window

### ISSUE THREAD

**Issue by dwightfry** [slhck/ffmpeg-progress-yield#17]
I utilized FfmpegProgress() in my code and it worked wonderfully. But after I compiled my project to .exe, a blank console window would open for each file that was being converted. After a lot of research, testing, and attempts to resolve this, I found only one solution that worked.

In the file ffmpeg_progress_yeild.py, I added the following line to the base_popen_kwargs dictionary:
"creationflags" : subprocess.CREATE_NO_WINDOW,

Perhaps you needn't include this by default, but there should be a way to call this option when it is needed.

**Comment by slhck** [comment]
I had issues setting this as a default for non-Windows environments. You can pass this flag yourself using the `popen_kwargs` option: https://htmlpreview.github.io/?https://github.com/slhck/ffmpeg-progress-yield/blob/master/docs/ffmpeg_progress_yield.html#FfmpegProgress.run_command_with_progress — I added this option specifically for this purpose, see #3
