### ISSUE TITLE
Unrecognized option 'stats_period'.

### ISSUE THREAD

**Issue by samanmohamadi** [slhck/ffmpeg-progress-yield#2]
After updating to v0.1.0 I get this Error: `Unrecognized option 'stats_period'.`
this also makes FFmpeg-normalize(which using this lib) crash too.

**Comment by slhck** [comment]
Thanks for the pointer. The method was only added in recent ffmpeg (after Dec. 2020). Please try to update the ffmpeg version for a quick fix.

I will make a change that removes the option again to keep backwards compatibility.

**Comment by slhck** [comment]
Fixed in v0.1.1.
