### ISSUE TITLE
quit() method is creating corrupted media

### ISSUE THREAD

**Issue by Akascape** [slhck/ffmpeg-progress-yield#5]
Hi @slhck ,
I am facing some **issues** with ffmpeg-progress-yield:
- **quit method is forcefully ending the process.**
I used the quit method to stop a conversion, but it just ended the ffmpeg process forcefully leaving a corrupted file. What I want is partial conversion which can be done by giving the command "Q" manually.
- **I want to give a direct string instead of a list as the command**
Giving a list is not bad but I feel like there should be a string method also to give the command to ffmpeg which will make the work easier.

**Something like this:**
```python
cmd = "ffmpeg -i '{file}' -c:v libx264 -y '{output}'"
ff = FfmpegProgress(cmd)
```
- **Showing the conversion logs in the console.**
I also want to show all the conversion logs of ffmpeg in the console, but don't know how to do it.

I hope you can do something 😢

**Comment by slhck** [comment]
> I used the quit method to stop a conversion, but it just ended the ffmpeg process forcefully leaving a corrupted file. What I want is partial conversion which can be done by giving the command "Q" manually.

I assumed that sending SIGINT would make it quit cleanly. You can use the `process.stdin` property to send any stdin to the process:

```python
ff = FfmpegProgress(TestLibrary.cmd)
for progress in ff.run_command_with_progress():
    print(f"{progress}/100")
    if progress > 50 and ff.process is not None:
        ff.process.communicate(input="q".encode())
        break
```

Does this work?

> Giving a list is not bad but I feel like there should be a string method also to give the command to ffmpeg which will make the work easier.

Passing a list of strings is the preferred way to handle subprocess commands (see also [the documentation](https://docs.python.org/3/library/subprocess.html#frequently-used-arguments)). This way, the arguments are properly escaped for the shell.

I will not support passing raw strings for this library.

If you want to use strings and call this library, you might be able to simply call `FfmpegProgress(cmd.split(' '))`. This may or may not work depending on whether your command arguments contain spaces or special characters.

> I also want to show all the conversion logs of ffmpeg in the console, but don't know how to do it.

Simply use:

```
ff.stderr
```

This will include all ffmpeg output.

**Comment by Akascape** [comment]
Thanks a lot @slhck !
> I assumed that sending SIGINT would make it quit cleanly. You can use the `process.stdin` property to send any stdin to the process:
> 
> ```python
> ff = FfmpegProgress(TestLibrary.cmd)
> for progress in ff.run_command_with_progress():
>     print(f"{progress}/100")
>     if progress > 50 and ff.process is not None:
>         ff.process.communicate(input="q".encode())
>         break
> ```
> 
> Does this work?

This method worked properly.

> I will not support passing raw strings for this library.

Its ok, I can manage it.

>Simply use:
>```
>ff.stderr
>```
>This will include all ffmpeg output.

This is giving the logs no doubt, but can I have the normal ffmpeg logs displayed in the console like when we use the simple subprocess method. Means I just want to show the live ffmpeg conversion in the console.
